In [2]:
import numpy as np
import pandas as pd


In [3]:
ash=pd.read_csv("StudentsPerformance.csv",encoding = "UTF-8")

In [6]:
lever = {'some college': 1,'high school': 2,"bachelor's degree":3,"associate's degree":4,"master's degree":5,'some high school':6} 

In [7]:
ash['parental level of education'] = [lever[item] for item in ash['parental level of education']]


In [8]:
for i in range(1000):
    if ash['gender'][i]=='male':
        ash['gender'][i]=1
    else:
        ash['gender'][i]=0


C:\Users\Ashish\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\Ashish\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [9]:
ash['gender'][0]

0

In [12]:
lk={'completed':1,'none':0}
ash['test preparation course']=[lk[item] for item in ash['test preparation course']]

In [201]:
lk={'group A':1,'group B':2,'group C':3,'group D':4,'group E':5}
ash['race/ethnicity']=[lk[item] for item in ash['race/ethnicity']]

In [205]:
lk={'standard':1,'free/reduced':2}
ash['lunch']=[lk[item] for item in ash['lunch']]

In [207]:

data=ash.drop(['math score','reading score', 'writing score'],axis=1)


In [20]:
import torch

In [328]:
from torch import nn,optim
import torch.nn.functional as F
class Classifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(5,8)
        self.fc2 = nn.Linear(8,9)
        self.fc3 = nn.Linear(9,12)
        self.fc4 = nn.Linear(12,3)
        
    def forward(self, x):
        # make sure input tensor is flattene
        x = F.sigmoid(self.fc1(x))
        x = F.sigmoid(self.fc2(x))
        x = F.sigmoid(self.fc3(x))
        x = self.fc4(x)
        return x
        
model=Classifier()    

In [329]:
a=data.values

In [330]:
a

array([[0, 2, 3, 1, 0],
       [0, 3, 1, 1, 1],
       [0, 2, 5, 1, 0],
       ...,
       [0, 3, 2, 2, 1],
       [0, 4, 1, 1, 1],
       [0, 4, 1, 2, 0]], dtype=object)

In [331]:
ak=a.astype(float)

In [332]:
ak

array([[0., 2., 3., 1., 0.],
       [0., 3., 1., 1., 1.],
       [0., 2., 5., 1., 0.],
       ...,
       [0., 3., 2., 2., 1.],
       [0., 4., 1., 1., 1.],
       [0., 4., 1., 2., 0.]])

In [333]:
train=torch.Tensor(ak)

In [334]:
train

tensor([[ 0.,  2.,  3.,  1.,  0.],
        [ 0.,  3.,  1.,  1.,  1.],
        [ 0.,  2.,  5.,  1.,  0.],
        ...,
        [ 0.,  3.,  2.,  2.,  1.],
        [ 0.,  4.,  1.,  1.,  1.],
        [ 0.,  4.,  1.,  2.,  0.]])

In [335]:
akas=model(train)

In [336]:
akas

tensor([[-0.2767,  0.3517,  0.8113],
        [-0.2765,  0.3512,  0.8105],
        [-0.2764,  0.3516,  0.8115],
        ...,
        [-0.2766,  0.3516,  0.8112],
        [-0.2760,  0.3512,  0.8104],
        [-0.2763,  0.3517,  0.8113]])

In [337]:
model

Classifier(
  (fc1): Linear(in_features=5, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=9, bias=True)
  (fc3): Linear(in_features=9, out_features=12, bias=True)
  (fc4): Linear(in_features=12, out_features=3, bias=True)
)

In [338]:
output=model(train)

In [339]:
out=output.float()
out

tensor([[-0.2767,  0.3517,  0.8113],
        [-0.2765,  0.3512,  0.8105],
        [-0.2764,  0.3516,  0.8115],
        ...,
        [-0.2766,  0.3516,  0.8112],
        [-0.2760,  0.3512,  0.8104],
        [-0.2763,  0.3517,  0.8113]])

In [340]:
labels=ash[['math score','reading score','writing score']]

In [341]:
labels1=labels.values

In [342]:
flabel=torch.Tensor(labels1).float()
output

tensor([[-0.2767,  0.3517,  0.8113],
        [-0.2765,  0.3512,  0.8105],
        [-0.2764,  0.3516,  0.8115],
        ...,
        [-0.2766,  0.3516,  0.8112],
        [-0.2760,  0.3512,  0.8104],
        [-0.2763,  0.3517,  0.8113]])

In [343]:
#criterion WORK
criterion=nn.L1Loss()##???WHY NLLLOSS Dint Work!!!!!!!!
optimizer=optim.Adam(model.parameters(),lr=0.003)



In [357]:
#traning Part
train_loss,test_loss=[],[]
running_loss=0
for e in range(50000):
    
    optimizer.zero_grad()
    output=model(train)
    loss=criterion(output,flabel)
    loss.backward()
    optimizer.step()
    running_loss+=loss.item()

In [358]:

running_loss

9.156929969787598

In [260]:
target=flabel.float()
output=output.float()

In [261]:
fklabel=flabel.long()

In [180]:
fklabel.shape

torch.Size([1000, 3])

In [181]:
fklabel.shape

torch.Size([1000, 3])

In [351]:
a=np.array([0,2,5,1,0])
ap=torch.Tensor(a)

In [352]:
data.head()

gender  race/ethnicity  parental level of education  lunch  \
0      0               2                            3      1   
1      0               3                            1      1   
2      0               2                            5      1   
3      1               1                            4      2   
4      1               3                            1      1   

   test preparation course  
0                        0  
1                        1  
2                        0  
3                        0  
4                        0

In [353]:
op=model.forward(ap)

In [354]:
op

tensor([ 60.3547,  69.2304,  70.0112])

In [355]:
ap

tensor([ 0.,  2.,  5.,  1.,  0.])

In [356]:
ash.head()

gender  race/ethnicity  parental level of education  lunch  \
0      0               2                            3      1   
1      0               3                            1      1   
2      0               2                            5      1   
3      1               1                            4      2   
4      1               3                            1      1   

   test preparation course  math score  reading score  writing score  
0                        0          72             72             74  
1                        1          69             90             88  
2                        0          90             95             93  
3                        0          47             57             44  
4                        0          76             78             75